package com.akun.koetomo;

/* This class is generated by JADX */
public final class R {

    public static final class mipmap {
        public static final int ic_launcher = 2130837504;
        public static final int ic_launcher_foreground = 2130837505;
    }

    public static final class color {
        public static final int ic_launcher_background = 2130903040;
    }

    public static final class string {
        public static final int app_name = 2130968576;
    }

    public static final class style {
        public static final int Theme_KoeTomo = 2131034112;
    }
}
