package com.akun.koetomo;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.security.MessageDigest;
import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;

// GENERATED by tools/gen_secrets.py — DO NOT EDIT.
// koetomo API key, obfuscated. Reconstructed only in memory at call time.
final class Secrets {
    private static final byte[] a0 = {-80, -79, -90, 67, -101, 102, 114, 37, -42, 105, -62, 45, 120, -93, -116, 7};
    private static final byte[] b0 = {99, -90, -47, 3, 26, 53, -44, -35, -24, -60, 10, -123, -123, -72, 19, 110};
    private static final byte[] a1 = {1, -19, -97, -56, 51, -75, 111, 81, -87, 116, 109, -79, -126, -109, -50, 112};
    private static final byte[] b1 = {72, -16, -38, 93, 94, -21, 31, 74, 38, 115, -89, 124, 80, -17, 125, 23};
    private static final byte[] a2 = {-74, 52, -25, -105, -72, 111, -26, 9, 75, -89, 29, 104, 43, -124, 16, -39};
    private static final byte[] b2 = {26, 113, 22, -97, -51, -109, -48, 39, -124, -54, -107, 114, -63, -55, -100, -43};
    private static final byte[] iv = {36, 57, 71, -105, 121, 50, 8, 120, -80, -28, -121, 56};
    private static final byte[] ct = {94, 92, 77, 39, -29, 54, -88, -60, 111, -100, 19, -89, -78, 1, -3, 38, 50, -97, -116, -29, -99, -43, 29, 25, 104, -28, -86, -24, 18, -12, -71, 66, 88, 84, 101, -117, -42, -43, -61, 23, -7, 108, 5, 57, -55, 35, -83, -47, -30, 13, -50, 27, -51, -80, -128, 81, 54, 87, -125, -42};
    private static final byte[] iv2 = {16, 44, -93, -76, 34, -17, -41, -43, 15, -78, -21, -106};
    private static final byte[] ct2 = {-37, -71, -24, 59, 9, -72, -127, -11, -101, 118, -34, 39, 89, 46, 84, -63, 54, 69, 71, -78, -17, -116, 4, -69, 45, -92, 78, 87, 52, -93, -51, -108, 126, 66, 73, 59, -48, 46, -61, -86, 70, -82, -64, -45, -70, -20, 108, -96, -86, -78};
    private static final int[] o = {2, 0, 1};

    private static Context ctx;
    static void init(Context c){ ctx = c == null ? null : c.getApplicationContext(); }

    private Secrets() {}

    private static byte[] cert(){ try{ PackageInfo pi=ctx.getPackageManager().getPackageInfo(ctx.getPackageName(), PackageManager.GET_SIGNATURES); byte[] raw=pi.signatures[0].toByteArray(); return MessageDigest.getInstance("SHA-256").digest(raw);}catch(Throwable t){ return new byte[0]; } }

    private static byte[] x(byte[] e, byte[] p){ byte[] r=new byte[e.length]; for(int i=0;i<e.length;i++) r[i]=(byte)(e[i]^p[i]); return r; }

    private static byte[] wrap() throws Exception {
        byte[][] sh = new byte[3][];
        sh[0]=x(a0,b0); sh[1]=x(a1,b1); sh[2]=x(a2,b2);
        MessageDigest md=MessageDigest.getInstance("SHA-256");
        for(int i=0;i<3;i++) md.update(sh[o[i]]);
        md.update(cert());
        return md.digest();
    }
    private static String open(byte[] ivv, byte[] c) {
        try {
            Cipher ci=Cipher.getInstance("AES/GCM/NoPadding");
            ci.init(Cipher.DECRYPT_MODE, new SecretKeySpec(wrap(),"AES"), new GCMParameterSpec(128, ivv));
            return new String(ci.doFinal(c), "UTF-8");
        } catch (Throwable t) { return ""; }
    }
    /** X(Twitter) OAuth2 のクライアントID(公開クライアント/PKCE)。同じ難読化で保持 */
    static String xClientId() { return open(iv2, ct2); }

    static String aesKey() {
        try {
            byte[][] sh = new byte[3][];
            sh[0]=x(a0,b0); sh[1]=x(a1,b1); sh[2]=x(a2,b2);
            byte[][] ord = new byte[3][];
            for(int i=0;i<3;i++) ord[i]=sh[o[i]];
            MessageDigest md=MessageDigest.getInstance("SHA-256");
            for(int i=0;i<3;i++) md.update(ord[i]);
            md.update(cert());
            byte[] wrap=md.digest();
            Cipher c=Cipher.getInstance("AES/GCM/NoPadding");
            c.init(Cipher.DECRYPT_MODE, new SecretKeySpec(wrap,"AES"), new GCMParameterSpec(128, iv));
            return new String(c.doFinal(ct), "UTF-8");
        } catch (Throwable t) { return ""; }
    }
}
